angular.module('ut.core.constants')
    .factory('professions', [
        'Profession',
        function (Profession) {
            return [
				new Profession(1, 'Akolita', 14, 'Posługa'),
                new Profession(2, 'Alchemik', 59, 'Eliksiry'),
				new Profession(3, 'Banita', 21, 'Przebiegłość'),
				new Profession(4, 'Barbarzyńca', 28, 'Krzepa'),
                new Profession(5, 'Bard', 21, 'Poetyckie kroniki'),
				new Profession(6, 'Berserker', 50, 'Szał'),
				new Profession(7, 'Czarny Rycerz', 55, 'Aura Śmierci'),
				new Profession(8, 'Czarodziej', 61, 'Rzucanie czarów'),
				new Profession(9, 'Czempion Królewski', 40, 'Wyspecjalizowanie'),
				new Profession(10, 'Druid', 58, 'Magiczny Menhir'),
				new Profession(11, 'Fałszywy Prorok', 55, 'Przeklęte Wizje'),
				new Profession(12, 'Giermek', 18, 'Odwrócenie uwagi'),
				new Profession(13, 'Gladiator', 25, 'Słaby punkt'),
				new Profession(14, 'Gwardzista', 32, 'Natarcie'),
				new Profession(15, 'Hiena cmentarna', 16, 'Znawca nekropolii'),
				new Profession(16, 'Kapłan', 62, 'Święta walka'),
				new Profession(17, 'Kleryk', 55, 'Modlitwy'),
				new Profession(18, 'Korsarz', 35, 'Zuchwała szarża'),
				new Profession(19, 'Łapserdak', 8, ''),
				new Profession(20, 'Łowca Czarownic', 44, 'Polowanie'),
				new Profession(21, 'Łowca Głów', 29, 'Atak na czerep'),
				new Profession(22, 'Łowca Nagród', 31, 'Wielka szansa'),
				new Profession(23, 'Mistrz Łuku', 35, 'Sokole oko'),
				new Profession(24, 'Mistrz miecza', 39, 'Perfekcja'),
				new Profession(25, 'Mnich', 21, 'Znawca świątyń'),
				new Profession(26, 'Nożownik', 26, 'Zasztyletowanie'),
				new Profession(27, 'Paladyn', 55, 'Aura Inspiracji'),
				new Profession(28, 'Podstępny kupiec', 28, 'Handlowanie'),
				new Profession(29, 'Przepatrywacz', 29, 'Znawca tropów'),
				new Profession(30, 'Rozbójnik', 31, 'Atak z zaskoczenia'),
				new Profession(31, 'Rusznikarz', 28, 'Rusznikarstwo'),
				new Profession(32, 'Rycerz zakonny', 55, 'Zakonna determinacja'),
				new Profession(33, 'Sierżant Strażników', 27, 'Chronić i służyć'),
				new Profession(34, 'Skald', 19, 'Bitewne pieśni'),
				new Profession(35, 'Skrytobójca', 39, 'Perfekcyjne zabójstwo'),
				new Profession(36, 'Strażnik Kniei', 25, 'Terenoznawstwo'),
				new Profession(37, 'Strzelec', 19, 'Strzał w ruchu'),
				new Profession(38, 'Szaman', 57, 'Rytuał'),
				new Profession(39, 'Szampierz', 34, 'Zamaszyste cięcie'),
				new Profession(40, 'Szarlatan', 23, 'Obłędna gadanina'),
				new Profession(41, 'Szermierz', 34, 'Zastawa'),
                new Profession(42, 'Topornik', 23, 'Siła ostrza'),
				new Profession(43, 'Uliczny Sędzia', 55, 'Ja jestem PRAWEM!!!'),
				new Profession(44, 'Uczeń Czarodzieja', 34, 'Przyuczenie'),
				new Profession(45, 'Wielki Łowczy', 24, 'Terenoznawstwo'),
				new Profession(46, 'Wojownik klanu', 27, 'Rytualna walka'),
				new Profession(47, 'Wróżbita', 18, 'Przewidywanie'),
				new Profession(48, 'Zabójca', 29, 'Perfekcyjny atak'),
                new Profession(49, 'Zbrojny', 31, 'Wyszkolenie'),
                new Profession(50, 'Zielarz', 18, 'Warzenia naparów/trucizn'),
                new Profession(51, 'Złodziej', 20, 'Doliniarstwo'),
                new Profession(52, 'Zwadźca', 35, 'Dwie bronie'),
                new Profession(53, 'Zwiadowca', 24, 'Skradanie')
                ];
        }]);